version: '3'

services:
  wordpress:
    build: .
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db # Servidor de bases de datos al que se conectará WordPress*
      WORDPRESS_DB_USER: wordpress # Usuario con el que WordPress se logeará en la base de datos (1) 
      WORDPRESS_DB_PASSWORD: wordpress # Contraseña del usuario especificado en la linea anterior (2)
      WORDPRESS_DB_NAME: wordpress # Nombre de la base de datos asociada a Wordpress (3)
      # * Se especifica "db" ya que este repositorio esta preparado para usar el contenedor "db" como servidor de
      #   bases de datos. Si usted va a usar otro servidor (localhost, servidor externo,...) debe cambiar este valor.
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mariadb:latest
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor # Contraseña del usuario root de la base de datos
      MYSQL_USER: wordpress # Usuario con el que WordPress va a logearse en la base de datos (1)
      MYSQL_PASSWORD: wordpress # Contraseña del usuario especificado en la linea anterior (2)
      MYSQL_DATABASE: wordpress # Nombre de la base de datos asociada a WordPress (3)
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  php:
    image: php:latest
    volumes:
      - php_data:/var/www/html
    networks:
      - my_network

networks:
  my_network:

volumes:
  wordpress_data:
  db_data:
  php_data:
