version: '3'

services:
  wordpress:
    build: .
    image: wordpress:latest
    ports:
      - 8080:80 # If port 8080 is being used on your machine by another service, modify this line and write the desired port to the left of the colon where you want to redirect the WordPress container.
    environment:
      WORDPRESS_DB_HOST: db # Database server that WordPress will connect to* (4)
      WORDPRESS_DB_USER: wordpress # User that WordPress will use to log in to the database (1) 
      WORDPRESS_DB_PASSWORD: wordpress # Password for the user specified in the previous line (2)
      WORDPRESS_DB_NAME: wordpress  # Name of the database associated with WordPress (3)
      # * Specify "db" as this repository is set up to use the "db" container as the database server. If you are using another server (localhost, external server,...), you should change this value.
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mariadb:latest
    ports:
      - 13306:3306 # If port 13306 is being used on your machine by another service, modify this line and write the desired port to the left of the colon where you want to redirect the WordPress container.
    environment:
      MYSQL_ROOT_PASSWORD: toor # Database root user password
      MYSQL_USER: wordpress # User that WordPress will use to log in to the database (1)
      MYSQL_PASSWORD: wordpress # Password for the user specified in the previous line (2)
      MYSQL_DATABASE: wordpress  # Name of the database associated with WordPress (3)
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  php:
    image: php:latest
    volumes:
      - php_data:/var/www/html
    networks:
      - my_network

networks:
  my_network:

volumes:
  wordpress_data:
  db_data:
  php_data:
